# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 983cbf51bf5ff4853f9cdf62bd21ae3863839eb93b97383043bf14a01a1545136259227977a15d91b985b05eaf89e120559affc06b9c1aaf8c7ceb6bcec32859

test:
  secret_key_base: 42172086306d72fc95bf99b3d7ef2c5b3f2ec3cf1d4d14bf40dd1c86ebe3cec3793e1f51d71b84879b9a34033e4c983958aee175caeb4424a93bb335ca96dc8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
